/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Link = {
  label?: string;
  href?: string;
};

export type Cta = {
  _type: "cta";
  heading?: string;
  text?: string;
  link?: Link;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type VideoGallery = {
  _type: "videoGallery";
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  videos?: Array<{
    vimeoId?: string;
    name?: string;
    categoryGroups?: Array<{
      group?: string;
      categories?: string;
      _type: "winningCategories";
      _key: string;
    }>;
    _type: "video";
    _key: string;
  }>;
};

export type Agenda = {
  _type: "agenda";
  title?: string;
  items?: Array<{
    time?: string;
    title?: string;
    text?: RichText;
    _type: "agendaItem";
    _key: string;
  }>;
};

export type CustomTab = {
  _type: "customTab";
  name?: string;
  content?: RichText;
};

export type AwardCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "awardCategory";
};

export type CompanyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "company";
};

export type Winner = {
  _type: "winner";
  categoryGroup?: string;
  category?: AwardCategoryReference;
  company?: CompanyReference;
};

export type CompanyGroup = {
  _type: "companyGroup";
  name?: string;
  companies?: Array<
    {
      _key: string;
    } & CompanyReference
  >;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type PersonGroup = {
  _type: "personGroup";
  name?: string;
  people?: Array<
    {
      _key: string;
    } & PersonReference
  >;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "research";
  body?: RichText;
  downloadThumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  downloadFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  downloadUrl?: string;
  authors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  partnerCategories?: Array<
    {
      _key: string;
    } & CompanyGroup
  >;
  legacyWpId?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  firstName?: string;
  lastName?: string;
  slug?: Slug;
  jobTitle?: string;
  companies?: Array<
    {
      _key: string;
    } & CompanyReference
  >;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: RichText;
  categories?: Array<string>;
  legacyWpId?: number;
};

export type AwardCategory = {
  _id: string;
  _type: "awardCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  categoryGroup?: string;
  description?: RichText;
};

export type ConferenceEvent = {
  _id: string;
  _type: "conferenceEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eventType?: "summit" | "briefing" | "webinar";
  body?: RichText;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  venue?: CompanyReference;
  country?: "AE" | "CH" | "GB" | "JE" | "SA" | "SG" | "US";
  startDate?: string;
  startTime?: string;
  endDate?: string;
  endTime?: string;
  timezoneCode?: string;
  hideDateTime?: boolean;
  speakerTypes?: Array<
    {
      _key: string;
    } & PersonGroup
  >;
  chairs?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  agenda?: Array<
    {
      _key: string;
    } & Agenda
  >;
  agendaText?: RichText;
  techDemos?: Array<{
    title?: string;
    company?: CompanyReference;
    description?: RichText;
    _type: "techDemo";
    _key: string;
  }>;
  sponsorTypes?: Array<
    {
      _key: string;
    } & CompanyGroup
  >;
  sponsorBenefits?: RichText;
  sponsorVideos?: VideoGallery;
  photographs?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  registerButtonLink?: string;
  register?: RichText;
  faqs?: RichText;
  customTabs?: Array<
    {
      _key: string;
    } & CustomTab
  >;
  legacyWpId?: number;
};

export type AwardsProgrammeGroupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "awardsProgrammeGroup";
};

export type AcclaimReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "acclaim";
};

export type AwardsProgramme = {
  _id: string;
  _type: "awardsProgramme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  programme?: AwardsProgrammeGroupReference;
  body?: RichText;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  venue?: CompanyReference;
  country?: "AE" | "CH" | "GB" | "JE" | "SA" | "SG" | "US";
  keyDates?: RichText;
  startDate?: string;
  startTime?: string;
  endDate?: string;
  endTime?: string;
  timezoneCode?: string;
  hideDateTime?: boolean;
  judgesIntro?: RichText;
  judgesPanels?: Array<
    {
      _key: string;
    } & PersonGroup
  >;
  nominationsOpeningDate?: string;
  nominationsClosingDate?: string;
  winnersAnnouncementDate?: string;
  categoriesContent?: RichText;
  winners?: Array<
    {
      _key: string;
    } & Winner
  >;
  finalists?: RichText;
  previousWinners?: RichText;
  awardWinnersSupplement?: RichText;
  acclaim?: AcclaimReference;
  charityPartners?: Array<
    {
      _key: string;
    } & CompanyReference
  >;
  sponsorTypes?: Array<
    {
      _key: string;
    } & CompanyGroup
  >;
  sponsorBenefits?: RichText;
  sponsorVideos?: VideoGallery;
  winnerVideos?: VideoGallery;
  highlightsVideoId?: string;
  highlightVideoThumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  hidePreviousYearsHighlightVideo?: boolean;
  photographs?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  registerButtonLink?: string;
  register?: RichText;
  faqs?: RichText;
  customTabs?: Array<
    {
      _key: string;
    } & CustomTab
  >;
  legacyWpId?: number;
};

export type Acclaim = {
  _id: string;
  _type: "acclaim";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  programme?: AwardsProgrammeGroupReference;
  thumbnailImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  issuuId?: string;
  embedCode?: string;
  legacyWpId?: number;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  websiteUrl?: string;
  about?: RichText;
  address?: string;
  googleMapLocation?: string;
  phoneNumber?: string;
  categories?: Array<string>;
  legacyWpId?: number;
};

export type AwardsProgrammeGroup = {
  _id: string;
  _type: "awardsProgrammeGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: RichText;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  legacyTermId?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brands?: Array<string>;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brand?:
    | "wealthbriefing"
    | "wealthbriefingasia"
    | "familywealthreport"
    | "clearview";
  title?: string;
  slug?: Slug;
  blocks?: Array<
    {
      _key: string;
    } & Cta
  >;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  key?: Slug;
  domain?: string;
  region?: "uk" | "asia" | "us" | "global";
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  brandColor?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Link
  | Cta
  | SanityImageAssetReference
  | VideoGallery
  | Agenda
  | CustomTab
  | AwardCategoryReference
  | CompanyReference
  | Winner
  | CompanyGroup
  | PersonReference
  | PersonGroup
  | RichText
  | SanityFileAssetReference
  | Resource
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Person
  | AwardCategory
  | ConferenceEvent
  | AwardsProgrammeGroupReference
  | AcclaimReference
  | AwardsProgramme
  | Acclaim
  | Company
  | AwardsProgrammeGroup
  | Post
  | Page
  | Brand
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: BRAND_QUERY
// Query: *[_type == "brand" && _id == $brandId][0]{    _id,    title,    key,    domain,    region,    logo,    brandColor  }
export type BRAND_QUERY_RESULT = {
  _id: string;
  title: string | null;
  key: Slug | null;
  domain: string | null;
  region: "asia" | "global" | "uk" | "us" | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  brandColor: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "page" && brand == $brand && slug.current == "home"][0]{    _id,    title,    blocks  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  blocks: Array<
    {
      _key: string;
    } & Cta
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug && brand == $brand][0]{    _id,    title,    blocks  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  blocks: Array<
    {
      _key: string;
    } & Cta
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && brand == $brand && defined(slug.current) && slug.current != "home"]{    "slug": slug.current  }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && $brand in brands] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    publishedAt,    excerpt,    image  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug && $brand in brands][0]{    _id,    title,    publishedAt,    excerpt,    image,    content  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current) && $brand in brands]{    "slug": slug.current  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "brand" && _id == $brandId][0]{\n    _id,\n    title,\n    key,\n    domain,\n    region,\n    logo,\n    brandColor\n  }\n': BRAND_QUERY_RESULT;
    '\n  *[_type == "page" && brand == $brand && slug.current == "home"][0]{\n    _id,\n    title,\n    blocks\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug && brand == $brand][0]{\n    _id,\n    title,\n    blocks\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && brand == $brand && defined(slug.current) && slug.current != "home"]{\n    "slug": slug.current\n  }\n': PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && $brand in brands] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    image\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug && $brand in brands][0]{\n    _id,\n    title,\n    publishedAt,\n    excerpt,\n    image,\n    content\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && $brand in brands]{\n    "slug": slug.current\n  }\n': POST_SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
