import type { Metadata } from 'next'
import { Onest } from 'next/font/google'

import './globals.css'

const onest = Onest({
  variable: '--font-onest',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'WealthBriefing Group',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${onest.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  )
}
