import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import { draftMode } from 'next/headers'
import { VisualEditing } from 'next-sanity/visual-editing'

import { SanityLive } from '@/sanity/live'

import './globals.css'

const onest = Onest({
  variable: '--font-onest',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'WealthBriefing Group',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: LayoutProps<'/'>) {
  const { isEnabled: isDraftMode } = await draftMode()

  return (
    <html
      lang="en"
      className={`${onest.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <SanityLive includeDrafts={isDraftMode} />
        {isDraftMode && <VisualEditing />}
      </body>
    </html>
  )
}
